[colors.bright]
black      =  "#7f8c8d"
blue       =  "#3daee9"
cyan       =  "#16a085"
green      =  "#1cdc9a"
magenta    =  "#8e44ad"
red        =  "#c0392b"
white      =  "#ffffff"
yellow     =  "#fdbc4b"

[colors.normal]
black      =  "#232627"
blue       =  "#1d99f3"
cyan       =  "#1abc9c"
green      =  "#11d116"
magenta    =  "#9b59b6"
red        =  "#ed1515"
white      =  "#fcfcfc"
yellow     =  "#f67400"

[colors.primary]
background =  "#232627"
foreground =  "#ffffff"
